In [7]:
import pandas as pd

df = pd.read_excel("rawData.xlsx")

df.head()

,Student ID,First Name,Last Name,Grade Level,Contact Phone,Math Grade,Science Grade,English Grade,Attendance Days,Total School Days,Enrollment Status
0,ST-1001,John,Smith,Grade 10,(555) 019-2831,88.0,92.0,85.0,175.0,180.0,Active
1,ST-1002,sarah,connor,10th,555.019.2832,95.0,NaN,91.0,160.0,180.0,Active
2,ST-1003,Michael,Brown,11,555-019-2833,72.0,68.0,74.0,NaN,180.0,Active
3,ST-1004,Emily,Davis,Grade 9,5550192834,NaN,88.0,90.0,178.0,180.0,Active
4,ST-1001,John,Smith,10th Grade,555-019-2831,88.0,92.0,85.0,175.0,180.0,Active

In [6]:
df.tail()

,Student ID,First Name,Last Name,Grade Level,Contact Phone,Math Grade,Science Grade,English Grade,Attendance Days,Total School Days,Enrollment Status
13,ST-1012,Megan,Martin,Grade 10,5550192842,87.0,83.0,89.0,179.0,180.0,Active
14,ST-1004,Emily,Davis,Grade 9,555-019-2834,90.0,88.0,90.0,178.0,180.0,Active
15,ST-1013,Kevin,Garcia,12,555.019.2843,76.0,79.0,81.0,162.0,180.0,Active
16,ST-1014,Rachel,Martinez,Grade 9,555-019-2844,98.0,NaN,94.0,NaN,180.0,Active
17,ST-1015,Daniel,Robinson,10th,555-019-2845,83.0,86.0,82.0,170.0,180.0,active

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         18 non-null     str
 1   First Name         18 non-null     str
 2   Last Name          18 non-null     str
 3   Grade Level        18 non-null     str
 4   Contact Phone      18 non-null     str
 5   Math Grade         15 non-null     float64
 6   Science Grade      15 non-null     float64
 7   English Grade      16 non-null     float64
 8   Attendance Days    15 non-null     float64
 9   Total School Days  16 non-null     float64
 10  Enrollment Status  18 non-null     str
dtypes: float64(5), str(6)
memory usage: 1.7 KB

In [9]:
df.isnull().sum()

Student ID           0
First Name           0
Last Name            0
Grade Level          0
Contact Phone        0
Math Grade           3
Science Grade        3
English Grade        2
Attendance Days      3
Total School Days    2
Enrollment Status    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["First Name"] = df["First Name"].str.title()
df["First Name"].unique()

<StringArray>
[   'John',   'Sarah', 'Michael',   'Emily',   'David', 'Jessica',   'James',
  'Amanda',  'Robert',    'Lisa',   'Brian',   'Megan',   'Kevin',  'Rachel',
  'Daniel']
Length: 15, dtype: str

In [15]:
df["Last Name"] = df["Last Name"].str.title()
df["Last Name"].unique()

<StringArray>
[   'Smith',   'Connor',    'Brown',    'Davis',   'Wilson',   'Taylor',
 'Anderson',   'Thomas',  'Jackson',    'White',   'Harris',   'Martin',
   'Garcia', 'Martinez', 'Robinson']
Length: 15, dtype: str

In [18]:
def cleanGrade(value):
    value = str(value).lower()
    
    if "9" in value:
        return "Grade 9"
    elif "10" in value:
        return "Grade 10"
    elif "11" in value:
        return "Grade 11"
    elif "12" in value:
        return "Grade 12"
    return value

df["Grade Level"] = df["Grade Level"].apply(cleanGrade)
df["Grade Level"].unique()

<StringArray>
['Grade 10', 'Grade 11', 'Grade 9', 'Grade 12']
Length: 4, dtype: str

In [19]:
df.dtypes

Student ID               str
First Name               str
Last Name                str
Grade Level              str
Contact Phone            str
Math Grade           float64
Science Grade        float64
English Grade        float64
Attendance Days      float64
Total School Days    float64
Enrollment Status        str
dtype: object

In [ ]:
df.isnull().sum()

clean_df = df.dropna(
    subset = ["Math Grade",
        "Science Grade",
        "English Grade",
        "Attendance Days",
        "Total School Days"
    ]
)

clean_df.isnull().sum()

Student ID           0
First Name           0
Last Name            0
Grade Level          0
Contact Phone        0
Math Grade           0
Science Grade        0
English Grade        0
Attendance Days      0
Total School Days    0
Enrollment Status    0
dtype: int64

In [26]:
clean_df["Enrollment Status"] = clean_df["Enrollment Status"].str.capitalize()
clean_df["Enrollment Status"].unique()

<StringArray>
['Active']
Length: 1, dtype: str

In [31]:
clean_df[clean_df.duplicated(subset = ["Student ID"], keep=False)]

,Student ID,First Name,Last Name,Grade Level,Contact Phone,Math Grade,Science Grade,English Grade,Attendance Days,Total School Days,Enrollment Status
0,ST-1001,John,Smith,Grade 10,(555) 019-2831,88.0,92.0,85.0,175.0,180.0,Active
4,ST-1001,John,Smith,Grade 10,555-019-2831,88.0,92.0,85.0,175.0,180.0,Active

In [33]:
clean_df["Contact Phone"] = clean_df["Contact Phone"].str.replace(r"\D","", regex=True)

In [35]:
clean_df[clean_df.duplicated(keep=False)]
clean_df = clean_df.drop_duplicates()

In [36]:
display(clean_df)

,Student ID,First Name,Last Name,Grade Level,Contact Phone,Math Grade,Science Grade,English Grade,Attendance Days,Total School Days,Enrollment Status
0,ST-1001,John,Smith,Grade 10,5550192831,88.0,92.0,85.0,175.0,180.0,Active
6,ST-1006,Jessica,Taylor,Grade 12,5550192836,91.0,94.0,96.0,180.0,180.0,Active
9,ST-1002,Sarah,Connor,Grade 10,5550192832,95.0,89.0,91.0,160.0,180.0,Active
10,ST-1009,Robert,Jackson,Grade 9,5550192839,79.0,85.0,88.0,168.0,180.0,Active
11,ST-1010,Lisa,White,Grade 11,5550192840,92.0,90.0,95.0,172.0,180.0,Active
13,ST-1012,Megan,Martin,Grade 10,5550192842,87.0,83.0,89.0,179.0,180.0,Active
14,ST-1004,Emily,Davis,Grade 9,5550192834,90.0,88.0,90.0,178.0,180.0,Active
15,ST-1013,Kevin,Garcia,Grade 12,5550192843,76.0,79.0,81.0,162.0,180.0,Active
17,ST-1015,Daniel,Robinson,Grade 10,5550192845,83.0,86.0,82.0,170.0,180.0,Active